### ISSUE TITLE
bug: schemas not being updated

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#41] opened 2024-02-22 10:24 UTC
When I edit the properties on the scheme on the annotation view (i.e. add another option to existing options) it does not get updated

**Comment by rsimon** [comment] 2024-02-22 11:19
I can't seem to reproduce this. Are you sure you clicked the 'Save' button after editing the metadata? Here's what I tried:

- I tagged a an annotation with an entity
- I clicked "Edit Schema" to edit this entity schema
- I added a new "Options" property (with two values) to the schema, which I called "Type"
- I saved the schema
- The editing form in the right sidebar was updated, and included the new "Type" field. I was able to choose from the two options I defined
- I clicked "Edit Schema" again, and added a third option to the "Type" field
- I saved the schema
- In the sidebar, I was able to pick the new, third option. Clicking 'Save' would properly store the option in the annotation.

Here's a video of this process. (Sorry for the low size/quality... hope it's visible enough). Are you doing something in a different way, or seeing different behavior?

https://github.com/rsimon/immarkus/assets/470971/592fff5a-561f-42bd-94b9-c031786e02b5

**Comment by StoIva** [comment] 2024-02-22 17:22
I will see with Sunkyu. I will send her your steps and see if she gets diffrent results

**Comment by rsimon** [comment] 2024-03-07 06:51
Revisiting this issue, it looks like this must be the same issue issue #62! The technical problem for this is now fixed. (Therefore I'm closing this issue.) What remains is the UX issue about how to best allow editing of parent properties in the annotation view, as discussed in #62.

**Closed by rsimon** 2024-03-07 06:51 UTC
Labels: bug
