### ISSUE TITLE
cannot access annotations in added image

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#59] opened 2024-02-28 11:52 UTC
Hi
![Screenshot (493)](https://github.com/rsimon/immarkus/assets/128056738/cd5738b1-3b43-4da2-a705-5ccd3167669b)
![Screenshot (492)](https://github.com/rsimon/immarkus/assets/128056738/a347275c-6e6f-4379-8abd-7af1ef63be50)

as the title says i cannot annotate the aded image and the list/selection seem to be showing the wrong thing

**Comment by rsimon** [comment] 2024-02-28 11:56
Hi Iva, 

- the annotation list (second screenshot) seems to display correct. If multiple images are in the workspaces, the lists collapse. If you click on one of the entries, does the list unfold and show the annotations for this image?
- in your first screenshot, it looks like you have selected an annotation which was tagged with two Entity Classes, but both entity classes have no schema properties defined. Can you confirm that "City Wall" and "Excavation" have properties in their schema?

**Comment by StoIva** [comment] 2024-02-28 14:07
yes, both have defined schemas. the problem seems to be only be affecting the annotation with two tags

**Comment by rsimon** [comment] 2024-02-28 14:20
Hm. Once again, I'm unable to reproduce this with my images/data. Can you share your data model file, and the two annotation files?

Also: did you try clicking the two entries in the annotation list? Did the lists unfold correctly and show the annotation cards?

**Comment by StoIva** [comment] 2024-02-28 14:39
Hi. yes sorry, the list view does work fine. the image with two tags will not allow me to access the properties

the image annotation file:
[图一扬州地形.json](https://github.com/rsimon/immarkus/files/14435499/default.json)

also, i got a json.crswap on that image. could that be the problem? do i delete? this image has a lot of info so i would not like to do this all over

**Comment by StoIva** [comment] 2024-02-28 14:40
*json.crswap in the immarkus folder that contains that image

**Comment by rsimon** [comment] 2024-02-29 12:26
Thanks for sending those @StoIva! 

Argh - so sorry this happened again. Another case where I forgot to set the option to include the inherited properties... This is now fixed!

Concerning the `.crswap` files: I haven't come across this before. But it looks like these are temporary files which Chrome writes while saving data (to your data model or annotation files). IMMARKUS does never read them directly, and Chrome would normally remove them. 

If there are any left, it might mean that Chrome got interrupted. E.g. if you have moved  an annotation and then immediately afterwards closed the browser. It's perfectly safe to delete them. The worst that can happen is that the last change might not have gotten stored to the actual .JSON file. But, as I said, only in rare cases. Otherwise, nothing should break.

**Closed** 2024-03-07 06:46 UTC
