### ISSUE TITLE
Undo of Delete and Create actions is not persisted

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#53] opened 2024-02-27 10:04 UTC
Hi
still cannot undo/redo any steps on an image once an image is added. also, the deleted annotations in the first image (and the added image) reappear after i close the add image view.

**Comment by StoIva** [comment] 2024-02-27 10:09
![Screenshot (478)](https://github.com/rsimon/immarkus/assets/128056738/d8bea153-91b2-48df-a49d-03fee2bdd31e)

**Comment by rsimon** [comment] 2024-02-27 10:10
Concerning the undo/redo issue: I haven't addressed this yet. The undo/redo stack is indeed re-created as soon as an image is added. (Because a whole new annotation view has to be created internally.) 

Making undo/redo steps from the single image view available to the new window view will be (fairly significant) extra work. How essential is this at this point? Can we defer this until after April 18, for example?

**Comment by rsimon** [comment] 2024-02-27 10:12
Concerning the second issue: can you describe your steps? Is there anything shown in the F12 browser console? I can't reproduce this either. Here's what I'm doing:

- Open image A 
- Open image B
- Delete an annotation from image B
- Close image A

All ok for me - the deleted annotation from image B does not re-appear. Is your process different?

**Comment by StoIva** [comment] 2024-02-27 10:41
Hi. we can defer the issue for april, sure.

What i did: 

- open image
- added image
- annotated one image
- annotated the other
- clicked undo to delete the annotation on the first one- the annotation disappeared
- clicked undo to delete the annotation on the second one- the annotation disappeared
- closed both
- reopened first- annotation reappears
- added second- annotation reappears

**Comment by rsimon** [comment] 2024-02-27 10:58
P.S.: I renamed this issue specifically for the delete/create problem, and created a separate issue here for the other task so we keep them both on the list separately: #56.

**Comment by rsimon** [comment] 2024-03-22 12:36
Hi @StoIva,

I finally got around to looking into this. Turns out this was a deeper-sitting bug in my core annotation library. This should be fixed now!

**Closed** 2024-03-25 07:39 UTC
Labels: bug
