### ISSUE TITLE
the screen is shaking once i select an image or entity class

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#85] opened 2024-04-16 12:41 UTC
Hi
I clicked on an entity class in the knowledge graph and the screen shakes

**Comment by rsimon** [comment] 2024-04-16 12:46
I hope it's only the graph that shakes :-) 

- You can move nodes by clicking and dragging them
- If you drag a single node, the rest of the graph (= all nodes) will re-arrange based on the automatic layout. (I believe this is what you mean by "shaking"?)
- Sometime if you click, but don't quite hit the node, the browser will interpret this as a (very small) drag event. In this case, you selection won't be triggered. You simply need to click again, without moving the mouse.

Most of this is default behavior of either your browser, or the graph engine. We can tweak things a l little further down the line, such as making the sensitive area around a node bigger, etc.

**Comment by rsimon** [comment] 2024-04-16 13:02
Sometimes if you make a very small movement, the browser will interpret this as a drag. (Could even be a problem with your mouse!) There's nothing I can change about this, since this is handled "below" the application, inside the browser. I'm pasting a screen-recording below.

First, I'm making a few small drags. I assume this is what you mean by shaking? Then, I'm clicking with the mouse, not moving it. Instead of triggering the graph layout, this will select the node, and open the details panel.

https://github.com/rsimon/immarkus/assets/470971/c1f2f5da-faeb-4621-9bca-fc7afd292b68

**Comment by StoIva** [comment] 2024-04-16 13:14
Hi
This is what i am seeing on my screen. i do not see this in your video. I don't have a screen recorder so apologies for the quality


https://github.com/rsimon/immarkus/assets/128056738/75fb0d7c-4675-4fac-8db3-e2aa19c792f1

**Comment by rsimon** [comment] 2024-04-16 13:26
Oh, wow :-) Thanks for making video - that helps. I haven't seen that myself. But I'll investigate what could cause it. Have you seen a similar behavior with the slide-out sidebar in the image gallery?

**Comment by rsimon** [comment] 2024-04-16 13:56
Hm, I wasn't able to find a situation where the same behavior occurs on my system. But I did make a small change which _might_ have an influence. Can you check again if it still happens?

**Comment by StoIva** [comment] 2024-04-16 14:02
no issues in the image gallery. i refereshed the page and tried immarkus in two browsers (chrome and edge) and still had the shakes

**Comment by rsimon** [comment] 2024-04-16 14:17
Still can't reproduce it, but think I might have found something. Can you try again?

**Comment by StoIva** [comment] 2024-04-16 14:55
did in two browsers, it is still shaking

**Comment by rsimon** [comment] 2024-04-16 15:39
Weird. I checked in Chrome and Edge, on Linux and MacOS. No problems there. (I don't have access to Windows.) I made more tweaks. Can you refresh your browser a few times and try again? If this doesn't help, I think the only thing we can do is to disable the slide animation.

**Comment by fonziedw** [comment] 2024-04-16 21:51
Hi Rainer,
I see that iva has been sending tons of questions that oftentimes take a
lot of time to deal with. I have asked her to first check with others or
test more than once before submitting these questions. I would like to ask
you also to ask her not to submit these to github but to make a list of
minor issues if any so that they do not take time away from our other
priorities. It is also important that she learns and teaches others to do
some problem solving herself before asking for help constantly.
Best,
Hilde

**Comment by rsimon** [comment] 2024-04-17 10:44
Ok, great!

**Closed by rsimon** 2024-04-17 10:44 UTC
