### ISSUE TITLE
properties on dropdown not being added

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#30] opened 2024-01-30 09:18 UTC
Hi
recently added things to the dropdown menu and now they don't work. the dropdown will dispalay them, but it will not let me click it.
Help

![Screenshot (409)](https://github.com/rsimon/immarkus/assets/128056738/04f9731f-e804-4183-a500-5c613fa20444)

**Comment by rsimon** [comment] 2024-01-30 09:36
I can't reproduce this either, so I believe (fingers crosses) this may be a side effect of issue #25. Let me know if you still see the issue after reloading your work folder with the latest IMMARKUS update.

**Comment by StoIva** [comment] 2024-01-30 10:02
works. thank you

**Comment by StoIva** [comment] 2024-01-30 10:50
update: seems to work great when adding to parent class, not in child class. forgot to check both. sorry

**Comment by rsimon** [comment] 2024-01-30 11:04
I tried these steps, which seemed to work for me. Can you check if this is different from what you are doing?

- I started with the `_immarkus.model.json` file from above. This includes (among others) a class `object` with an options field `date dynasty`. (Same as your screenshot, but the values were different in my case?)
- In the image annotation view, I tagged a selection as `object`, picked a value from `date dynasty`, clicked save.
- I deselected the annotation and reselected - the value was still there. Same if I reloaded the application via browser refresh.

Second test: 
- I repeated the same steps, but tagged the selection as `city_wall`, which is a child of `object`. Same effect - everything got stored correctly.

Is your workflow different?

**Comment by StoIva** [comment] 2024-01-30 12:18
the problem was that i could not even select the option, and that it was (in some cases) not even appearing on the dropdown. i seem to not have that problem now, i will let you know if that changes

**Comment by rsimon** [comment] 2024-01-30 12:20
Ok, weird. Yes, let's keep an eye on it. If it happens again, do definitely check the F12 browser console, to see if any error messages are listed.

**Comment by rsimon** [comment] 2024-02-13 12:59
I think we can close this one, too, for now. Feel free to re-open in case the issue re-surfaces.

**Closed by rsimon** 2024-02-13 12:59 UTC
