### ISSUE TITLE
annotation card not showing more information

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#57] opened 2024-02-27 13:12 UTC
Hi
the annotation card in list (annotation view) is still just showing the entity (sub)class. i saw in your email that this has been changed to show the first two values of the schema but that is not seen on my screen or Sunkyu's.
we refreshed our pages and there was no change

**Comment by rsimon** [comment] 2024-02-27 13:15
Are you testing on immarkus.rainersimon.io (not immarkus.xmarkus.org)? Can you send the data model file + an annotation file?

**Comment by StoIva** [comment] 2024-02-27 13:18
yes. but the xmarkus.org link does not have scrollable add image? or is this a refresh page issue?

**Comment by StoIva** [comment] 2024-02-27 13:21
[_immarkus.model.json](https://github.com/rsimon/immarkus/files/14420070/_immarkus.model.json)

**Comment by rsimon** [comment] 2024-02-27 13:24
Ah - thanks for this. I can see what's going on. It's not showing values of the inherited props. Fix coming up soon!

**Comment by StoIva** [comment] 2024-02-27 13:24
and the add image on xmarkus.org page?

**Comment by rsimon** [comment] 2024-02-27 13:32
Brent will only update immarkus.xmarkus.org on demand. (I believe he has to do it manually.) Which means he'll only do it when there's a new formal release. Only the version on immarkus.rainersimon.io will be "live" as far as the latest bugfixes and feature additions are concerned.

**Comment by rsimon** [comment] 2024-02-27 13:34
The problem is now fixed: first few properties will now show up in the list (also for inherited properties). Also, I saw there were issues with the buttons (edit and delete) not working. Also fixed on immarkus.rainersimon.io now!

**Closed** 2024-02-27 17:52 UTC
